# Generated by Django 4.1.12 on 2024-04-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nature',
            old_name='tempature',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='weather',
        ),
    ]
